apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniserve-ingress
  namespace: default
  labels:
    app: miniserve
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: public
  rules:
  - host: miniserve.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: miniserve-clusterip
            port:
              number: 80