apiVersion: v1
kind: PersistentVolume
metadata:
  name: miniserve-data-pv
  namespace: default
  labels:
    app: miniserve
    type: data
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "k8s-hostpath"
  hostPath:
    path: /k8s/miniserve/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: miniserve-uploads-pv
  labels:
    app: miniserve
    type: uploads
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "k8s-hostpath"
  hostPath:
    path: /k8s/miniserve/uploads
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniserve-data
  namespace: default
  labels:
    app: miniserve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "k8s-hostpath"
  selector:
    matchLabels:
      app: miniserve
      type: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniserve-uploads
  namespace: default
  labels:
    app: miniserve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "k8s-hostpath"
  selector:
    matchLabels:
      app: miniserve
      type: uploads